version: 2
jobs:
  test1:
    docker:
      - image: circleci/golang:1.15-node
    working_directory: /go/src/github.com/fatedier/frp
    steps:
      - checkout
      - run: make
      - run: make alltest
      - store_artifacts:
          path: /go/src/github.com/fatedier/frp/bin
      
  test2:
    docker:
      - image: circleci/golang:1.14-node
    working_directory: /go/src/github.com/fatedier/frp
    steps:
      - checkout
      - run: make -f Makefile.cross-compiles
      - store_artifacts:
          path: /go/src/github.com/fatedier/frp/release/
      

workflows:
  version: 2
  build_and_test:
    jobs:
      - test1
      - test2
